### ISSUE TITLE
Permissions errors block functionality on private sites

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/wp-desktop#408]
Edit by @rachelmcr to summarize the issues detailed below (here and in comments):

~API requests for a number of endpoints return 403 errors for private sites, which breaks functionality in the desktop app. (This is a desktop-only issue; it does not affect Calypso web.)~

The endpoint issues have been fixed, but some permission errors persist as noted below.

Affected endpoints/features:

* ~`post-counts` (Post counts aren't returned for blog posts, feedback, CPTs)~ Fixed
* ~`activity` (Activity Log doesn't load)~ Fixed
* ~`gutenberg` (Editor doesn't load)~ Fixed
* Individual media items may not load, e.g. in the media modal (not an API response error; individual 403 responses from server for each image requested)
* Post preview shows logged-out view

---

Original report:

## URL/Version

Version 3.2.0 Beta (macOS)

## What I expected

When opening the Media Library in the beta Desktop App, the thumbnail images for the items in the Media Library should display correctly.

## Steps to reproduce

Opened the Media Library for the same site in the browser. The thumbnails are correctly rendered. See below:

![media_ _paul_jacobson_s_p2_ _wordpress_com](https://user-images.githubusercontent.com/2912202/35486714-c4d26dce-047a-11e8-8e70-f121ff1b349c.png)

## What happened instead

The Media Library view in the Desktop App doesn't display thumbnail images correctly. Most of the thumbnails are broken images. See below:

![media_ _paul_jacobson_s_p2_ _wordpress_com](https://user-images.githubusercontent.com/2912202/35486703-9e8adb92-047a-11e8-99d1-575ba97afe86.png)

**Comment by rachelmcr** [comment]
Thanks for the report! Do the images stay broken, for example after closing and restarting the app or logging out and logging back in to your account?

It may also help to check the console to see what is preventing the images from loading — on the Mac app you can open the console using `CTRL + SHIFT + i` to check for errors.

**Comment by pauljacobson** [comment]
Hi @rachelmcr 

I just opened the app again. Almost all of the thumbnails loaded this time although I also received these errors in the console:

```
https://public-api.wordpress.com/wpcom/v2/sites/3027893/post-counts/post Failed to load resource: the server responded with a status of 403 ()
:41050/posts/pauljacobson.wordpress.com:1 XMLHttpRequest cannot load https://public-api.wordpress.com/wpcom/v2/sites/3027893/post-counts/post. Response for preflight has invalid HTTP status code 403
build.js:257388 Uncaught TypeError: Cannot read property 'src' of null
    at Object.onCookieAuthComplete (build.js:257388)
    at emitOne (events.js:96)
    at EventEmitter.emit (events.js:188)
https://public-api.wordpress.com/rest/v1.1/pinghub/wpcom/me/newest-note-data Failed to load resource: the server responded with a status of 404 ()
admin-bar-hours-scale-2x.php Failed to load resource: the server responded with a status of 403 ()
https://edge.quantserve.com/quant.js Failed to load resource: net::ERR_INSECURE_RESPONSE
IMG-20180120-WA0021.jpg Failed to load resource: the server responded with a status of 403 ()
IMG-20180120-WA0011.jpg Failed to load resource: the server responded with a status of 403 ()
IMG-20180120-WA0000.jpg Failed to load resource: the server responded with a status of 403 ()
https://public-api.wordpress.com/rest/v1.1/pinghub/wpcom/me/newest-note-data Failed to load resource: the server responded with a status of 404 ()
build.js:768717 GET https://public-api.wordpress.com/rest/v1.1/pinghub/wpcom/me/newest-note-data 404 ()
```

**Comment by rachelmcr** [comment]
I believe the media issue is one symptom of a larger issue with private sites. I just ran into the same issue in the media section, as well as the logged-out view when previewing a blog post on a private site:

![screenshot 2018-02-21 12 12 56](https://user-images.githubusercontent.com/8658164/36479651-5340c3c4-1701-11e8-92ae-6bd644e0cd82.png)

**Comment by rachelmcr** [comment]
Another issue came up with private sites during beta testing for 3.7.0-beta1 (internal ref: p5T066-Hz-p2). In this case it was related to post counts — on private sites, the post count is always 0.

In the console, I'm seeing a 403 error on requests made to the `post-counts` endpoint as reported in https://github.com/Automattic/wp-desktop/issues/408#issuecomment-361834021.

**Comment by rachelmcr** [comment]
Another issue with private sites raised in testing for 3.7.0-beta1:

Activity Log doesn't work on private sites. Requests made to the `activity` endpoint returns a 403 error.

**Comment by rachelmcr** [comment]
I ran into another issue with this while testing 3.8.0-beta1:

Now that we check to see if a user has opted in to try Gutenberg, the entire screen freezes when I try to open the editor in the app for private sites. It fails on the API request to the Gutenberg opt-in endpoint, with this console error:

`XMLHttpRequest cannot load https://public-api.wordpress.com/wpcom/v2/sites/SITE_ID/gutenberg. Response for preflight has invalid HTTP status code 403`

**Comment by kwight** [comment]
To replicate these failures, download the repo and switch to the `release/*` branch (eg. `release/3.8.0`) and run `make dev`. To recover from the white screen on restart, first edit `~/Library/Application\ Support/WordPress.com/settings.json` and change the last location entry from `/post` to `/`.

**Comment by kwight** [comment]
Trying to run this down, one thing that sticks out is that the API calls send a `cookie` header but not an `authorization` header (eg. `authorization: X-WPCOOKIE ...`), which, as little as I know about API auth, would explain the fail. _Why_ the calls don't have that header, I have to dig further (this doesn't seem to be the case with users that have a mix of private and not-private sites).

**Comment by mmtr** [comment]
Nice finding @kwight!

I also noticed that the requests to the `wpcom/v2` endpoints are using the `OPTIONS` method which is not a valid method for the `post-counts` or `gutenberg` endpoints, causing issues with both public and private sites:

- If the site is private, the API returns a 403 error code which causes the white screen.
- If the site is public, the API returns a 200 success code but, since the response doesn't contain useful because of the `OPTIONS` method, we cannot check the selected editor we don't display the opt-in dialog.
<img width="973" alt="screen shot 2018-12-18 at 12 34 51" src="https://user-images.githubusercontent.com/1233880/50151507-60f31d80-02c1-11e9-8f33-1238cfca7baa.png">

I wonder if this is caused by the `wpcom.js` library used by the desktop application, which apparently is the [`node` version](https://github.com/Automattic/wp-calypso/blob/deae686b55f91ea6c7008f7ffe1f28dcdcb8ea64/client/lib/wp/node.js) instead of the [`browser` one](https://github.com/Automattic/wp-calypso/blob/deae686b55f91ea6c7008f7ffe1f28dcdcb8ea64/client/lib/wp/browser.js). 

I'll further investigate this.

**Comment by digitalwaveride** [comment]
Here is another user reporting  issues with the Mac Desktop app, when the site is in private mode.
Same issue, or likely something else?

User comment:

> Updated my wordpress desktop app on my macbook, but i'm now
> not able to create, edit, or view any posts or pages. 

[User is on wordpress.com/posts/drafts/ and tries to edit a draft.]
> (...) showing the blue banner at the top and the menu to the left, I click the dots and then edit and the screen changes to a page without the banner and menu, but doesn’t bring up a screen to edit. This is the same as with blog posts, I can either publish them or send to trash, but I can't edit or preview.

#user-report
#1650549-zen

**Comment by mmtr** [comment]
I continued investigating this and I realized that the `OPTIONS` requests are [`CORS` preflighted requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Preflighted_requests). And this doesn't happen only with requests to `wpcom/v2` endpoints, it occurs with all the requests.

However, I don't see these `CORS` preflighted requests when accessing WordPress.com directly on the browser, so it looks a specific problem in the desktop application.

Further more, only the `wpcom/v2` `CORS` preflighted requests are getting 403 errors if the site is private. 

So, to recap:
- If the site is public:
  - There is a `CORS` preflighted request before any request to the API.
  - The API returns a 200 status code for all the endpoints (`rest/v1.1`, `rest/v1.2`, `wpcom/v2`), so the browser determines the actual request is safe.
  - The actual request is performed which contains the appropriate authorization header (`authorization: Bearer ...`).
- If the site is private:
  - There is a `CORS` preflighted request before any request to the API.
  - The API returns a 200 status code only for the `rest/v1.1` and `rest/v1.2` endpoints.
  - The API returns a 403 status code only for the `wpcom/v2` endpoints.
  - The browser only finds safe the `rest/v1.1` and `rest/v1.2` requests, so `wpcom/v2` requests are not performed.

Having that in consideration I believe this could be fixed by either preventing the `CORS` preflighted requests or fixing the API in order to return 200 status codes for the `wpcom/v2` `CORS` preflighted requests.

I'm going to start exploring both of them and will post a comment as soon as I have an update.

**Comment by kwight** [comment]
Patch ready for review in D22595-code.

**Comment by vindl** [comment]
Fix deployed in D22595-code.

**Comment by rachelmcr** [comment]
@thehenrybyrd reported (and I confirmed) that in version 3.9.0-beta1 there are still problems with authentication on private sites — media not loading, post previews showing a logged-out state, etc.

**Comment by kwight** [comment]
Hm, with my desktop app set to the beta channel, and showing v3.9 beta 1, I can't replicate; I can load all of my media, and make new posts with no problems. Any other details, steps to replicate?

**Comment by rachelmcr** [comment]
Ah, are you testing with your a8c account? I'm seeing this issue with a non-a8c test account, nothing else I can think of as a factor — just logging in to the app and seeing these issues.

I just tried logging in with my a8c account and I see that the same private site accessed from that account has no issues; media loads, preview works, etc. Did the fix perhaps rely on something a8c-specific?

**Comment by kwight** [comment]
> Ah, are you testing with your a8c account?

Oh, I was! Thanks for the reminder 🙃 

I'm still not getting the endpoint problems from the original post, but I _do_ have permission errors with media and post preview. I think we've basically got a slew of (related? unrelated?) issues with authentication in the app for private sites, and our last fix above just took care of one category of them.

@rachelmcr is this what you're seeing too, or do you still see endpoint issues? (You can ignore the `newest-note-data`, that's a separate unrelated thing.)

Images in the Media Modal are giving me `403: Access Denied This file requires authorization: You must be logged in and a member of this blog.`.

**Comment by rachelmcr** [comment]
> I'm still not getting the endpoint problems from the original post, but I do have permission errors with media and post preview.

Ah yeah, you're right — no more endpoint issues, just other permission errors for media and post preview. Thanks for checking!

**Comment by gwwar** [comment]
@rachelmcr is this still high priority? @kwight were you actively working on this?

In the future I'd recommend opening up a new issue for any missed cases, and link back to the original. There's less overhead in understanding what needs to be done.

**Comment by kwight** [comment]
Not actively – I was hoping I might find a quick, easy explanation, but that wasn't the case.

**Comment by rachelmcr** [comment]
No, we've fixed the high priority bugs and the remaining issues are not as critical. Thanks to everyone who worked on this one!

> In the future I'd recommend opening up a new issue for any missed cases, and link back to the original. There's less overhead in understanding what needs to be done.

Good feedback, thanks. This was a weird one because the issue expanded to include the endpoint issues that have been fixed and now we're back to just the bug that was in the original report, so I didn't think to create a new issue. I'll go ahead and open a new issue for this now, to avoid confusion about what's still needed.
